//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickToLightData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APIResponse()
        {
            this.APIResponseMessages = new HashSet<APIResponseMessage>();
            this.SkidBuildOrderResponses = new HashSet<SkidBuildOrderResponse>();
            this.ShipmentLoadTrailerResponses = new HashSet<ShipmentLoadTrailerResponse>();
        }
    
        public int ID { get; set; }
        public string Exception { get; set; }
        public Nullable<int> Code { get; set; }
        public string ConfirmationNumber { get; set; }
        public string ConfirmedOrderNumber { get; set; }
        public string ConfirmedOrderSupplierCode { get; set; }
        public string ConfirmedOrderPlant { get; set; }
        public string ConfirmedOrderDockCode { get; set; }
        public string ConfirmedTrailerSupplierCode { get; set; }
        public string ConfirmedTrailerRoute { get; set; }
        public string ConfirmedTrailerRun { get; set; }
        public string ConfirmedTrailerNumber { get; set; }
        public Nullable<System.DateTime> ConfirmedTrailerPickUp { get; set; }
        public string HTTPCode { get; set; }
        public string HTTPMessage { get; set; }
        public string HTTPMoreInformation { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APIResponseMessage> APIResponseMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkidBuildOrderResponse> SkidBuildOrderResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentLoadTrailerResponse> ShipmentLoadTrailerResponses { get; set; }
    }
}
