//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickToLightData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIResponseMessage
    {
        public int ID { get; set; }
        public int APIResponseID { get; set; }
        public string KeyObject { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual APIResponse APIResponse { get; set; }
    }
}
