//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickToLightData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string Source { get; set; }
        public string ThreadName { get; set; }
        public Nullable<int> ThreadID { get; set; }
        public string Data { get; set; }
        public System.DateTime Created { get; set; }
    }
}
