//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickToLightData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAMC_TRPT_CrossRef
    {
        public int ID { get; set; }
        public string NAMCDestination { get; set; }
        public string TRPT { get; set; }
        public string SupplierCode { get; set; }
        public bool PullTrackerReport { get; set; }
    }
}
